'use client';

import React from 'react';
import { DashboardMetrics, DataMetric } from './dataParser';

export interface DashboardConfig {
  title: string;
  description: string;
  layout: 'grid' | 'cards' | 'mixed';
  components: ComponentConfig[];
}

interface ComponentConfig {
  type: 'metric' | 'chart' | 'distribution' | 'insights';
  title: string;
  data?: DataMetric[];
  metricIndex?: number;
  fullWidth?: boolean;
}

// Generate dashboard configuration from metrics
export function generateDashboardConfig(metrics: DashboardMetrics): DashboardConfig {
  return {
    title: 'Data Analytics Dashboard',
    description: metrics.summary,
    layout: 'mixed',
    components: [
      // Top metrics cards
      ...metrics.topMetrics.map((metric, idx) => ({
        type: 'metric' as const,
        title: metric.name,
        data: [metric],
        metricIndex: idx,
        fullWidth: false
      })),
      // Time series chart if available
      ...(metrics.timeSeries && metrics.timeSeries.length > 0
        ? [{
            type: 'chart' as const,
            title: 'Trend Analysis',
            fullWidth: true
          }]
        : []),
      // Insights section
      {
        type: 'insights' as const,
        title: 'Key Insights',
        fullWidth: true
      }
    ]
  };
}

// MetricCard Component
export function MetricCard({ metric }: { metric: DataMetric }) {
  const trendColor = (metric.trend || 0) > 0 ? 'text-green-500' : 'text-red-500';
  const trendIcon = (metric.trend || 0) > 0 ? '📈' : '📉';

  return (
    <div className="bg-gradient-to-br from-blue-50 to-cyan-50 rounded-lg p-6 border border-cyan-200 hover:shadow-lg transition-shadow">
      <div className="flex justify-between items-start">
        <div>
          <p className="text-sm font-medium text-slate-600">{metric.name}</p>
          <p className="text-3xl font-bold text-slate-900 mt-2">
            {typeof metric.value === 'number'
              ? metric.value.toLocaleString('en-US', {
                  maximumFractionDigits: 2
                })
              : metric.value}
            <span className="text-lg ml-1">{metric.unit}</span>
          </p>
        </div>
        <div className={`text-2xl font-bold ${trendColor}`}>
          {trendIcon} {metric.trend}%
        </div>
      </div>
    </div>
  );
}

// Simple Line Chart Component
export function TrendChart({ data }: { data: Array<{ timestamp: string; value: number }> }) {
  if (!data || data.length === 0) return null;

  const maxValue = Math.max(...data.map(d => d.value));
  const chartHeight = 200;

  return (
    <div className="bg-white rounded-lg p-6 border border-slate-200">
      <h3 className="text-lg font-semibold mb-4 text-slate-900">Trend Analysis</h3>
      <div className="flex items-end gap-1 justify-between h-64">
        {data.map((point, idx) => (
          <div
            key={idx}
            className="flex-1 bg-gradient-to-t from-cyan-400 to-blue-500 rounded-t hover:opacity-80 transition-opacity relative group"
            style={{
              height: `${(point.value / maxValue) * chartHeight}px`
            }}
          >
            <div className="absolute -top-6 left-1/2 -translate-x-1/2 bg-slate-900 text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap">
              {point.value}
            </div>
          </div>
        ))}
      </div>
      <div className="flex justify-between mt-4 text-xs text-slate-500">
        <span>{data[0]?.timestamp}</span>
        <span>{data[data.length - 1]?.timestamp}</span>
      </div>
    </div>
  );
}

// Insights Component
export function InsightsSection({ summary }: { summary: string }) {
  return (
    <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-lg p-6 border border-purple-200">
      <h3 className="text-lg font-semibold mb-3 text-slate-900">📊 Key Insights</h3>
      <p className="text-slate-700 leading-relaxed">{summary}</p>
      <div className="mt-4 text-sm text-slate-600 bg-white rounded p-3 border border-purple-100">
        <strong>Analysis generated by AI Agent:</strong> This summary is based on your uploaded data with statistical analysis and trend detection.
      </div>
    </div>
  );
}

// Main Dashboard Component
export function DynamicDashboard({ metrics }: { metrics: DashboardMetrics }) {
  const config = generateDashboardConfig(metrics);

  return (
    <div className="space-y-6">
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-slate-900">{config.title}</h1>
        <p className="text-slate-600 mt-2">{config.description}</p>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {metrics.topMetrics.map((metric, idx) => (
          <MetricCard key={idx} metric={metric} />
        ))}
      </div>

      {/* Charts and Insights */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {metrics.timeSeries && metrics.timeSeries.length > 0 && (
          <div className="lg:col-span-2">
            <TrendChart data={metrics.timeSeries} />
          </div>
        )}
        <div className={metrics.timeSeries ? '' : 'lg:col-span-3'}>
          <InsightsSection summary={metrics.summary} />
        </div>
      </div>
    </div>
  );
}
